# Lazygit configuration with Catppuccin Macchiato theme

gui:
  # Main panel
  theme:
    lightTheme: false
    activeBorderColor:
      - "#8aadf4"  # Blue
      - bold
    inactiveBorderColor:
      - "#6e738d"  # Overlay0
    optionsTextColor:
      - "#8aadf4"  # Blue
    selectedLineBgColor:
      - "#363a4f"  # Surface0
    selectedRangeBgColor:
      - "#363a4f"  # Surface0
    cherryPickedCommitBgColor:
      - "#f5a97f"  # Peach
    cherryPickedCommitFgColor:
      - "#24273a"  # Base
    unstagedChangesColor:
      - "#ed8796"  # Red
    defaultFgColor:
      - "#cad3f5"  # Text
    searchingActiveBorderColor:
      - "#eed49f"  # Yellow
      - bold

  # Window dimensions
  windowSize: 'normal'
  scrollHeight: 2
  scrollPastBottom: true
  sidePanelWidth: 0.3333
  expandFocusedSidePanel: false
  mainPanelSplitMode: 'flexible'
  enlargedSideViewLocation: 'left'

  # Mouse support
  mouseEvents: true

  # Language
  language: 'auto'

  # Time format
  timeFormat: '02 Jan 06 15:04 MST'
  shortTimeFormat: '15:04'

  # Border style
  border: 'rounded'

  # Animated loading
  animateExplosion: true

  # Show command log
  showCommandLog: true

  # Show bottom line
  showBottomLine: true

  # Show file tree
  showFileTree: true

  # Show list footer
  showListFooter: true

  # Show random tip
  showRandomTip: true

  # Experimental features
  experimentalShowBranchHeads: false

git:
  # Paging
  paging:
    colorArg: always
    pager: 'delta --dark --paging=never'
    useConfig: false

  # Commit settings
  commit:
    signOff: false
    autoWrapCommitMessage: true
    autoWrapWidth: 72

  # Merging
  merging:
    manualCommit: false
    args: ''

  # Pull settings
  pull:
    mode: 'merge'

  # Skip hooks
  skipHookPrefix: WIP

  # Auto fetch
  autoFetch: true
  autoRefresh: true

  # Log settings
  log:
    order: 'topo-order'
    showGraph: 'when-maximised'
    showWholeGraph: false

  # Diff settings
  diffContextSize: 3

update:
  method: prompt
  days: 14

refresher:
  refreshInterval: 10
  fetchInterval: 60

confirmOnQuit: false

quitOnTopLevelReturn: false

disableStartupPopups: false

notARepository: 'prompt'

promptToReturnFromSubprocess: true

keybinding:
  universal:
    quit: 'q'
    quit-alt1: '<c-c>'
    return: '<esc>'
    quitWithoutChangingDirectory: 'Q'
    togglePanel: '<tab>'
    prevItem: '<up>'
    nextItem: '<down>'
    prevItem-alt: 'k'
    nextItem-alt: 'j'
    prevPage: ','
    nextPage: '.'
    gotoTop: '<'
    gotoBottom: '>'
    scrollLeft: 'H'
    scrollRight: 'L'
    prevBlock: '<left>'
    nextBlock: '<right>'
    prevBlock-alt: 'h'
    nextBlock-alt: 'l'
    jumpToBlock: ['1', '2', '3', '4', '5']
    nextMatch: 'n'
    prevMatch: 'N'
    optionMenu: 'x'
    optionMenu-alt1: '?'
    select: '<space>'
    goInto: '<enter>'
    openRecentRepos: '<c-r>'
    confirm: '<enter>'
    remove: 'd'
    new: 'n'
    edit: 'e'
    openFile: 'o'
    scrollUpMain: '<pgup>'
    scrollDownMain: '<pgdown>'
    scrollUpMain-alt1: 'K'
    scrollDownMain-alt1: 'J'
    scrollUpMain-alt2: '<c-u>'
    scrollDownMain-alt2: '<c-d>'
    executeCustomCommand: ':'
    createRebaseOptionsMenu: 'm'
    pushFiles: 'P'
    pullFiles: 'p'
    refresh: 'R'
    createPatchOptionsMenu: '<c-p>'
    nextTab: ']'
    prevTab: '['
    nextScreenMode: '+'
    prevScreenMode: '_'
    undo: 'z'
    redo: '<c-z>'
    filteringMenu: '<c-s>'
    diffingMenu: 'W'
    diffingMenu-alt: '<c-e>'
    copyToClipboard: '<c-o>'
    submitEditorText: '<enter>'
    appendNewline: '<a-enter>'
    extrasMenu: '@'
    toggleWhitespaceInDiffView: '<c-w>'
    increaseContextInDiffView: '}'
    decreaseContextInDiffView: '{'